import { supabase } from '@/src/services/supabase';
import { getWellnessSummary } from '@/src/services/wellness';
import { Recommendation, WellnessSummary, RecommendationCategory } from '@/src/types/wellness';

function mapDbRecToModel(row: any): Recommendation {
  return {
    id: row.id,
    title: row.title,
    body: row.body,
    category: row.category as RecommendationCategory,
    priority: row.priority,
    generatedAt: row.generated_at,
    dismissed: row.dismissed,
    completed: row.completed,
  };
}

function buildRecommendations(summary: WellnessSummary): Recommendation[] {
  const now = new Date().toISOString();
  const recs: Recommendation[] = [];

  if (summary.sleepHours < 7) {
    recs.push({
      id: '', // Will be generated by database
      title: 'Extend your sleep window',
      body: 'Your sleep average is below 7 hours. Try a 30-minute earlier wind-down routine and limit screens after 9 PM.',
      category: 'sleep',
      priority: 1,
      generatedAt: now,
      dismissed: false,
      completed: false,
    });
  }

  if (summary.stressIndex > 55) {
    recs.push({
      id: '',
      title: 'Reset with a 5-minute trace pause',
      body: 'Stress signals are elevated. A short breathing exercise can reduce cortisol patterns detected in your metadata trace.',
      category: 'mindfulness',
      priority: 2,
      generatedAt: now,
      dismissed: false,
      completed: false,
    });
  }

  if (summary.activityLevel < 50) {
    recs.push({
      id: '',
      title: 'Add a 15-minute movement block',
      body: 'Activity levels are trending low. A brief walk can improve mood and sleep quality within 24 hours.',
      category: 'activity',
      priority: 3,
      generatedAt: now,
      dismissed: false,
      completed: false,
    });
  }

  recs.push({
    id: '',
    title: 'Review your weekly wellness trace',
    body: `Your composite wellness score is ${summary.wellnessScore}. Check Trends to spot patterns MindTrace can help you optimize.`,
    category: 'general',
    priority: 4,
    generatedAt: now,
    dismissed: false,
    completed: false,
  });

  return recs.sort((a, b) => a.priority - b.priority);
}

export async function getRecommendations(userId: string): Promise<Recommendation[]> {
  const { data, error } = await supabase
    .from('recommendations')
    .select('*')
    .eq('user_id', userId)
    .eq('dismissed', false)
    .order('priority', { ascending: true });

  if (error) {
    console.error('Failed to fetch recommendations:', error);
    return [];
  }

  return (data || []).map(mapDbRecToModel);
}

export async function generateRecommendations(userId: string): Promise<Recommendation[]> {
  const summary = await getWellnessSummary(userId);
  const recs = buildRecommendations(summary);

  const dbRows = recs.map((r) => ({
    user_id: userId,
    title: r.title,
    body: r.body,
    category: r.category,
    priority: r.priority,
    generated_at: r.generatedAt,
    dismissed: r.dismissed,
    completed: r.completed,
  }));

  // Clear existing non-dismissed ones to avoid duplicates
  await supabase
    .from('recommendations')
    .delete()
    .eq('user_id', userId)
    .eq('dismissed', false);

  const { data, error } = await supabase
    .from('recommendations')
    .insert(dbRows)
    .select();

  if (error) {
    console.error('Failed to generate recommendations:', error);
  }

  return (data || []).map(mapDbRecToModel);
}

export async function dismissRecommendation(userId: string, id: string): Promise<void> {
  const { error } = await supabase
    .from('recommendations')
    .update({ dismissed: true })
    .eq('id', id)
    .eq('user_id', userId);

  if (error) {
    console.error('Failed to dismiss recommendation:', error);
  }
}

export async function completeRecommendation(userId: string, id: string): Promise<void> {
  const { error } = await supabase
    .from('recommendations')
    .update({ completed: true })
    .eq('id', id)
    .eq('user_id', userId);

  if (error) {
    console.error('Failed to complete recommendation:', error);
  }
}
